//TCG(Sagas):
export const CMP_FETCH_DATA = {REQ:'CMP_FETCH_DATA_REQUEST', OK:'CMP_FETCH_DATA_SUCCESS', FAIL:'CMP_FETCH_DATA_FAILURE'}
export const CMP_ACT_TWO = {REQ:'CMP_ACT_TWO_REQUEST', OK:'CMP_ACT_TWO_SUCCESS', FAIL:'CMP_ACT_TWO_FAILURE'}

//Simply an action:
export const CMP_SET_MODPREFIX = 'CMP_SET_UNIQUE_MODULE_PREFIX'
export const CMP_INC_SIZE = 'CMP_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'
