//PROMOS(Sagas):
export const PROMOS_FETCH_DATA = {REQ:'PROMOS_FETCH_DATA_REQUEST', OK:'PROMOS_FETCH_DATA_SUCCESS', FAIL:'PROMOS_FETCH_DATA_FAILURE'}
export const PROMOS_ACT_TWO    = {REQ:'PROMOS_ACT_TWO_REQUEST',    OK:'PROMOS_ACT_TWO_SUCCESS',    FAIL:'PROMOS_ACT_TWO_FAILURE'}
//Just a PROMOS action:
export const PROMOS_SET_MODPREFIX = 'PROMOS_SET_UNIQUE_MODULE_PREFIX'
export const PROMOS_INC_SIZE      = 'PROMOS_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//CATALOGUE(Sagas):
export const CATALOGUE_FETCH_DATA = {REQ:'CATALOGUE_FETCH_DATA_REQUEST', OK:'CATALOGUE_FETCH_DATA_SUCCESS', FAIL:'CATALOGUE_FETCH_DATA_FAILURE'}
export const CATALOGUE_ACT_TWO    = {REQ:'CATALOGUE_ACT_TWO_REQUEST',    OK:'CATALOGUE_ACT_TWO_SUCCESS',    FAIL:'CATALOGUE_ACT_TWO_FAILURE'}
//Just a CATALOGUE action:
export const CATALOGUE_SET_MODPREFIX = 'CATALOGUE_SET_UNIQUE_MODULE_PREFIX'

//CAT_ITEM(Sagas):
export const CAT_ITEM_FETCH_DATA = {REQ:'CAT_ITEM_FETCH_DATA_REQUEST', OK:'CAT_ITEM_FETCH_DATA_SUCCESS', FAIL:'CAT_ITEM_FETCH_DATA_FAILURE'}
export const CAT_ITEM_ACT_TWO    = {REQ:'CAT_ITEM_ACT_TWO_REQUEST',    OK:'CAT_ITEM_ACT_TWO_SUCCESS',    FAIL:'CAT_ITEM_ACT_TWO_FAILURE'}
//Just a CAT_ITEM action:
export const CAT_ITEM_SET_MODPREFIX = 'CAT_ITEM_SET_UNIQUE_MODULE_PREFIX'
export const CAT_ITEM_FLIP_CARD     = 'CAT_ITEM_FLIP_THE_PRODUCT_CARD'

//CAT_GROUP(Sagas):
export const CAT_GROUP_FETCH_DATA = {REQ:'CAT_GROUP_FETCH_DATA_REQUEST', OK:'CAT_GROUP_FETCH_DATA_SUCCESS', FAIL:'CAT_GROUP_FETCH_DATA_FAILURE'}
export const CAT_GROUP_ACT_TWO    = {REQ:'CAT_GROUP_ACT_TWO_REQUEST',    OK:'CAT_GROUP_ACT_TWO_SUCCESS',    FAIL:'CAT_GROUP_ACT_TWO_FAILURE'}
//Just a CAT_GROUP action:
export const CAT_GROUP_SET_MODPREFIX = 'CAT_GROUP_SET_UNIQUE_MODULE_PREFIX'

//USER_HOME(Sagas):
export const USER_HOME_FETCH_DATA = {REQ:'USER_HOME_FETCH_DATA_REQUEST', OK:'USER_HOME_FETCH_DATA_SUCCESS', FAIL:'USER_HOME_FETCH_DATA_FAILURE'}
export const USER_HOME_ACT_TWO    = {REQ:'USER_HOME_ACT_TWO_REQUEST',    OK:'USER_HOME_ACT_TWO_SUCCESS',    FAIL:'USER_HOME_ACT_TWO_FAILURE'}
//Just a USER_HOME action:
export const USER_HOME_SET_MODPREFIX = 'USER_HOME_SET_UNIQUE_MODULE_PREFIX'
export const USER_HOME_INC_SIZE      = 'USER_HOME_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//NEWS_FEED(Sagas):
export const NEWS_FEED_FETCH_DATA = {REQ:'NEWS_FEED_FETCH_DATA_REQUEST', OK:'NEWS_FEED_FETCH_DATA_SUCCESS', FAIL:'NEWS_FEED_FETCH_DATA_FAILURE'}

//UI(Sagas):
export const UI_FETCH_DATA = {REQ:'UI_FETCH_DATA_REQUEST', OK:'UI_FETCH_DATA_SUCCESS', FAIL:'UI_FETCH_DATA_FAILURE'}
export const UI_STORE_DATA = {REQ:'UI_STORE_DATA_REQUEST', OK:'UI_STORE_DATA_SUCCESS', FAIL:'UI_STORE_DATA_FAILURE'}
//UI syncronous actions:
export const UI_SIDEBAR_TOGGLE                = 'UI_SIDEBAR_TOGGLE_VISIBILITY_STATE'
export const UI_SIDEBAR_CLICK_ITEM            = 'UI_SIDEBAR_CLICK_MENU_ITEM'

export const UI_TOP_NAVBAR_CLICK_ITEM         = 'UI_TOP_NAVBAR_CLICK_A_MENU_ITEM'

export const UI_NEWS_FEED_CLICK_ITEM          = 'UI_NEWS_FEED_CLICK_A_NEWS_ITEM'
export const UI_NEWS_FEED_PULL                = 'UI_NEWS_FEED_PULL_DOWN_TO_REFRESH_THE_FEED'

export const UI_CATALOGUE_CLICK_ITEM_FLIP     = 'UI_CATALOGUE_CLICK_ITEM_TO_FLIP'
export const UI_CATALOGUE_CLICK_ITEM_BUY      = 'UI_CATALOGUE_CLICK_ITEM_TO_BUY'
export const UI_CATALOGUE_CLICK_ITEM_FAV      = 'UI_CATALOGUE_CLICK_ITEM_TO_TOGGLE_FAVORITE_STATUS'
export const UI_CATALOGUE_CLICK_ITEM_SHARE    = 'UI_CATALOGUE_CLICK_ITEM_TO_SHARE_THE_ITEM'
export const UI_CATALOGUE_CLICK_REVIEW        = 'UI_CATALOGUE_CLICK_AN_EXISTING_REVIEW_FOR_THE_ITEM'
export const UI_CATALOGUE_CLICK_NEW_REVIEW    = 'UI_CATALOGUE_CLICK_TO_CREATE_A_NEW_REVIEW_FOR_THE_ITEM'
export const UI_CATALOGUE_CLICK_SIM_OR_REC    = 'UI_CATALOGUE_CLICK_ON_AN_ITEM_FROM_SIMILAR_OR_RECOMMENDED_LISTS'

export const UI_LOGIN_TOGGLE_CHECKBOX_REM_ME  = 'UI_LOGIN_TOGGLE_CHECKBOX_TO_REMEMEBER_CREDENTIALS'
export const UI_LOGIN_SUBMIT                  = 'UI_LOGIN_SUBMIT_LOGIN_CREDENTIALS'
export const UI_LOGIN_SUBMIT_OUT              = 'UI_LOGIN_SUBMIT_LOGOUT_DIRECTIVE'
export const UI_LOGIN_TOGGLE_LOGIN_REG        = 'UI_LOGIN_TOGGLE_LOGIN_OR_REGISTER_FORMS'

export const UI_LOGIN_REG_SUBMIT              = 'UI_LOGIN_REG_SUBMIT_REGISTRATION_FORM'
export const UI_LOGIN_REG_NEW_EMAIL           = 'UI_LOGIN_REG_NEW_EMAIL_HAS_BEEN_TYPED_IN'
export const UI_LOGIN_REG_NEW_PW              = 'UI_LOGIN_REG_NEW_PASSWORD_CHARACTER_HAS_BEEN_TYPED_IN_PRIMARY_PASSWORD_BOX'
export const UI_LOGIN_REG_NEW_SECONDARY_PW    = 'UI_LOGIN_REG_NEW_PASSWORD_CHARACTER_HAS_BEEN_TYPED_IN_SECONDARY_PASSWORD_BOX'
export const UI_LOGIN_REG_SEX_SEL             = 'UI_LOGIN_REG_SEX_SELECTION_RADIO_BUTTONS_TOGGLED'
export const UI_LOGIN_REG_NEW_BIRTHDAY        = 'UI_LOGIN_REG_NEW_DATE_OF_BIRTH_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_NEW_F               = 'UI_LOGIN_REG_NEW_SURNAME_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_NEW_I               = 'UI_LOGIN_REG_NEW_FIRSTNAME_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_NEW_O               = 'UI_LOGIN_REG_NEW_PATRONYMIC_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_NEW_ID_DOC_SEL      = 'UI_LOGIN_REG_NEW_ID_DOCUMENT_TYPE_HAS_BEEN_SELECTED'
export const UI_LOGIN_REG_NEW_ID_DOC_DAT      = 'UI_LOGIN_REG_NEW_ID_DOCUMENT_DATA_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_NEW_PHONE           = 'UI_LOGIN_REG_NEW_PHONE_NUMBER_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_PREF_COMM_SEL       = 'UI_LOGIN_REG_PREFERRED_COMMUNICATION_METHOD_HAS_BEEN_CHOSEN'
export const UI_LOGIN_REG_PREF_COMM_COM       = 'UI_LOGIN_REG_PREFERRED_COMMUNICATION_METHODS_COMMENT_HAS_BEEN_ENTERED'
export const UI_LOGIN_REG_WHATSAPP_TIE_IN     = 'UI_LOGIN_REG_WHATSAPP_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_VIBER_TIE_IN        = 'UI_LOGIN_REG_VIBER_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_TELEGRAM_TIE_IN     = 'UI_LOGIN_REG_TELEGRAM_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_SKYPE_TIE_IN        = 'UI_LOGIN_REG_SKYPE_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_INSTAGRAM_TIE_IN    = 'UI_LOGIN_REG_INSTAGRAM_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_FB_TIE_IN           = 'UI_LOGIN_REG_FB_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_VK_TIE_IN           = 'UI_LOGIN_REG_VK_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_ODNOKL_TIE_IN       = 'UI_LOGIN_REG_ODNOKLASSNIKI_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_TUMBLR_TIE_IN       = 'UI_LOGIN_REG_TUMBLR_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_PINTEREST_TIE_IN    = 'UI_LOGIN_REG_PINTEREST_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_LINKEDIN_TIE_IN     = 'UI_LOGIN_REG_LINKEDIN_ACCOUNT_TIE_IN_ICON_CLICKED'
export const UI_LOGIN_REG_NEW_HOME_ADDRESS    = 'UI_LOGIN_REG_NEW_CHARACTER_IN_HOME_ADDRESS_HAS_BEEN_TYPED'
export const UI_LOGIN_REG_NEW_SECRET_Q_SEL    = 'UI_LOGIN_REG_NEW_SECRET_QUESTION_HAS_BEEN_CHOSEN_FROM_THE_LIST'
export const UI_LOGIN_REG_NEW_SECRET_Q        = 'UI_LOGIN_REG_NEW_SECRET_QUESTION_HAS_BEEN_CREATED_BY_USER'
export const UI_LOGIN_REG_NEW_SECRET_ANSWER   = 'UI_LOGIN_REG_NEW_ANSWER_TO_CURRENT_SECRET_QUESTION_HAS_BEEN_ENTERED'
