//CMP(Sagas):
export const CMP_FETCH_DATA = {REQ:'CMP_FETCH_DATA_REQUEST', OK:'CMP_FETCH_DATA_SUCCESS', FAIL:'CMP_FETCH_DATA_FAILURE'}
export const CMP_ACT_TWO = {REQ:'CMP_ACT_TWO_REQUEST', OK:'CMP_ACT_TWO_SUCCESS', FAIL:'CMP_ACT_TWO_FAILURE'}
//Just a CMP action:
export const CMP_SET_MODPREFIX = 'CMP_SET_UNIQUE_MODULE_PREFIX'
export const CMP_INC_SIZE = 'CMP_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//PROMOS(Sagas):
export const PROMOS_FETCH_DATA = {REQ:'PROMOS_FETCH_DATA_REQUEST', OK:'PROMOS_FETCH_DATA_SUCCESS', FAIL:'PROMOS_FETCH_DATA_FAILURE'}
export const PROMOS_ACT_TWO = {REQ:'PROMOS_ACT_TWO_REQUEST', OK:'PROMOS_ACT_TWO_SUCCESS', FAIL:'PROMOS_ACT_TWO_FAILURE'}
//Just a PROMOS action:
export const PROMOS_SET_MODPREFIX = 'PROMOS_SET_UNIQUE_MODULE_PREFIX'
export const PROMOS_INC_SIZE = 'PROMOS_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//CATALOGUE(Sagas):
export const CATALOGUE_FETCH_DATA = {REQ:'CATALOGUE_FETCH_DATA_REQUEST', OK:'CATALOGUE_FETCH_DATA_SUCCESS', FAIL:'CATALOGUE_FETCH_DATA_FAILURE'}
export const CATALOGUE_ACT_TWO = {REQ:'CATALOGUE_ACT_TWO_REQUEST', OK:'CATALOGUE_ACT_TWO_SUCCESS', FAIL:'CATALOGUE_ACT_TWO_FAILURE'}
//Just a CATALOGUE action:
export const CATALOGUE_SET_MODPREFIX = 'CATALOGUE_SET_UNIQUE_MODULE_PREFIX'
export const CATALOGUE_INC_SIZE = 'CATALOGUE_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//CAT_ITEM(Sagas):
export const CAT_ITEM_FETCH_DATA = {REQ:'CAT_ITEM_FETCH_DATA_REQUEST', OK:'CAT_ITEM_FETCH_DATA_SUCCESS', FAIL:'CAT_ITEM_FETCH_DATA_FAILURE'}
export const CAT_ITEM_ACT_TWO = {REQ:'CAT_ITEM_ACT_TWO_REQUEST', OK:'CAT_ITEM_ACT_TWO_SUCCESS', FAIL:'CAT_ITEM_ACT_TWO_FAILURE'}
//Just a CAT_ITEM action:
export const CAT_ITEM_SET_MODPREFIX = 'CAT_ITEM_SET_UNIQUE_MODULE_PREFIX'
export const CAT_ITEM_INC_SIZE = 'CAT_ITEM_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//CAT_GROUP(Sagas):
export const CAT_GROUP_FETCH_DATA = {REQ:'CAT_GROUP_FETCH_DATA_REQUEST', OK:'CAT_GROUP_FETCH_DATA_SUCCESS', FAIL:'CAT_GROUP_FETCH_DATA_FAILURE'}
export const CAT_GROUP_ACT_TWO = {REQ:'CAT_GROUP_ACT_TWO_REQUEST', OK:'CAT_GROUP_ACT_TWO_SUCCESS', FAIL:'CAT_GROUP_ACT_TWO_FAILURE'}
//Just a CAT_GROUP action:
export const CAT_GROUP_SET_MODPREFIX = 'CAT_GROUP_SET_UNIQUE_MODULE_PREFIX'
export const CAT_GROUP_INC_SIZE = 'CAT_GROUP_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'

//USER_HOME(Sagas):
export const USER_HOME_FETCH_DATA = {REQ:'USER_HOME_FETCH_DATA_REQUEST', OK:'USER_HOME_FETCH_DATA_SUCCESS', FAIL:'USER_HOME_FETCH_DATA_FAILURE'}
export const USER_HOME_ACT_TWO = {REQ:'USER_HOME_ACT_TWO_REQUEST', OK:'USER_HOME_ACT_TWO_SUCCESS', FAIL:'USER_HOME_ACT_TWO_FAILURE'}
//Just a USER_HOME action:
export const USER_HOME_SET_MODPREFIX = 'USER_HOME_SET_UNIQUE_MODULE_PREFIX'
export const USER_HOME_INC_SIZE = 'USER_HOME_INCREMENT_COMPONENTS_WIDTH_AND_HEIGHT_BY_ONE'
